[2025-08-17 15:08:42] 🟢 프로그램 시작
[2025-08-17 15:17:34] 🟢 프로그램 시작
[2025-08-17 15:17:34] 🟡 prevConfig.json이 없습니다. 초기 설정을 진행합니다.
[2025-08-17 15:17:38] 🟢 초기 설정 완료: prevConfig.json 생성됨
[2025-08-17 15:18:57] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\paul\Desktop\dev\파이썬qt\app\main.py", line 187, in <module>
    except:
    
KeyboardInterrupt

[2025-08-17 15:20:02] 🟢 프로그램 시작
[2025-08-17 15:20:11] 🟢 프로그램 시작
[2025-08-17 15:20:22] 🟢 초기 설정 완료: prevConfig.json 생성됨
[2025-08-17 15:20:30] 🟢 prevConfig.json 내용을 불러왔습니다
[2025-08-17 15:21:43] 🟢 프로그램 시작
[2025-08-17 15:23:58] 🟢 프로그램 시작
[2025-08-17 15:24:20] 🟢 프로그램 시작
[2025-08-17 15:25:02] 🟢 프로그램 시작
[2025-08-17 15:25:21] 🟢 프로그램 시작
[2025-08-17 15:27:55] 🟢 프로그램 시작
[2025-08-17 15:28:01] 🟢 5개 파일 선택됨
[2025-08-17 15:29:57] 🟢 프로그램 시작
[2025-08-17 15:31:31] 🟢 프로그램 시작
[2025-08-17 15:33:27] 🟢 프로그램 시작
[2025-08-17 15:33:54] 🟢 프로그램 시작
[2025-08-17 15:34:25] 🟢 프로그램 시작
[2025-08-17 15:37:52] 🟢 프로그램 시작
[2025-08-17 15:39:20] 🟢 프로그램 시작
[2025-08-17 15:39:48] 🟢 프로그램 시작
[2025-08-17 15:40:40] 🟢 프로그램 시작
[2025-08-17 15:40:44] 🟢 프로그램 시작
[2025-08-17 15:43:54] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\paul\Desktop\dev\파이썬qt\app\main.py", line 299, in <module>
    close_btn.clicked.connect(dialog.accept)
         ^^^^^^^^^^
KeyboardInterrupt

[2025-08-17 15:43:57] 🟢 프로그램 시작
[2025-08-18 11:11:21] 🟢 프로그램 시작
[2025-08-18 11:11:49] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 193, in run_copy
    final_target = copy_images(file_names, source, target, self.log)
  File "C:\Users\myh\Desktop\dev\copyImage\app\copy_utils.py", line 7, in copy_images
    os.makedirs(target_dir, exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 217, in makedirs
  File "<frozen os>", line 217, in makedirs
  File "<frozen os>", line 227, in makedirs
PermissionError: [WinError 5] 액세스가 거부되었습니다: 'C:/Users/paul'

[2025-08-18 11:12:05] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 193, in run_copy
    final_target = copy_images(file_names, source, target, self.log)
  File "C:\Users\myh\Desktop\dev\copyImage\app\copy_utils.py", line 7, in copy_images
    os.makedirs(target_dir, exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 217, in makedirs
  File "<frozen os>", line 217, in makedirs
  File "<frozen os>", line 227, in makedirs
PermissionError: [WinError 5] 액세스가 거부되었습니다: 'C:/Users/paul'

[2025-08-18 11:12:23] 🟢 prevConfig.json 내용을 불러왔습니다
[2025-08-18 11:12:26] 🟢 prevConfig.json 내용을 불러왔습니다
[2025-08-18 11:13:28] 🟢 4개 파일 선택됨
[2025-08-18 11:13:29] 📁 대상 폴더 생성: C:/Users/myh/Desktop/오답노트2
[2025-08-18 11:13:29] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:13:29] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:13:29] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:13:29] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:13:29] ✅ 작업 완료!
[2025-08-18 11:16:41] 🟢 프로그램 시작
[2025-08-18 11:16:44] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:16:44] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:16:44] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:16:44] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:16:44] ✅ 작업 완료!
[2025-08-18 11:20:43] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 312, in <module>
    sys.exit(app.exec())
             ~~~~~~~~^^
KeyboardInterrupt

[2025-08-18 11:20:46] 🟢 프로그램 시작
[2025-08-18 11:20:55] 🟢 prevConfig.json 내용을 불러왔습니다
[2025-08-18 11:21:01] 🟢 prevConfig.json 내용을 불러왔습니다
[2025-08-18 11:23:53] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 312, in <module>
    close_btn.clicked.connect(dialog.accept)
         ^^^^^^^^^^
KeyboardInterrupt

[2025-08-18 11:24:14] 🟢 프로그램 시작
[2025-08-18 11:24:43] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 326, in <module>
KeyboardInterrupt

[2025-08-18 11:24:44] 🟢 프로그램 시작
[2025-08-18 11:26:01] 🟢 프로그램 시작
[2025-08-18 11:26:37] 🟢 프로그램 시작
[2025-08-18 11:27:23] 🟢 프로그램 시작
[2025-08-18 11:27:39] 🟢 프로그램 시작
[2025-08-18 11:28:10] 🟢 프로그램 시작
[2025-08-18 11:29:04] 🟢 프로그램 시작
[2025-08-18 11:30:48] 🟢 프로그램 시작
[2025-08-18 11:30:58] ❌ 모든 항목을 입력해주세요
[2025-08-18 11:34:00] 🟢 프로그램 시작
[2025-08-18 11:34:02] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:34:02] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:34:02] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:34:02] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:34:02] ✅ 작업 완료!
[2025-08-18 11:34:12] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:34:12] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:34:12] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:34:12] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:34:12] ✅ 작업 완료!
[2025-08-18 11:34:15] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:34:15] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:34:15] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:34:15] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:34:15] ✅ 작업 완료!
[2025-08-18 11:35:41] 🟢 프로그램 시작
[2025-08-18 11:35:43] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:35:43] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:35:43] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:35:43] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:35:43] ✅ 작업 완료!
[2025-08-18 11:35:50] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:35:50] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:35:50] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:35:50] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:35:50] ✅ 작업 완료!
[2025-08-18 11:38:18] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 339, in <module>
    sys.app_window = window  # 전역에서 예외 처리용
             ^^^^^^^^^^
KeyboardInterrupt

[2025-08-18 11:38:19] 🟢 프로그램 시작
[2025-08-18 11:40:42] 🟢 프로그램 시작
[2025-08-18 11:40:54] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:40:54] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:40:54] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:40:54] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:40:54] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 233, in run_copy
    if explorer_action.isChecked() and sys.platform == "win32":
       ^^^^^^^^^^^^^^^
NameError: name 'explorer_action' is not defined. Did you mean: 'self.explorer_action'?

[2025-08-18 11:42:18] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 344, in <module>
    if __name__ == "__main__":
                 ^^^^^^^^^^
KeyboardInterrupt

[2025-08-18 11:42:20] 🟢 프로그램 시작
[2025-08-18 11:42:26] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:42:26] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:42:26] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:42:26] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:42:26] ✅ 작업 완료!
[2025-08-18 11:42:32] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:42:32] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:42:32] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:42:32] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:42:32] ✅ 작업 완료!
[2025-08-18 11:43:53] 🟢 프로그램 시작
[2025-08-18 11:44:24] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 360, in <module>
    sys.exit(app.exec())
             ~~~~~~~~^^
KeyboardInterrupt

[2025-08-18 11:44:25] 🟢 프로그램 시작
[2025-08-18 11:44:28] ❌ 폴더 띄우기 옵션 체크 해제됨
[2025-08-18 11:44:30] ✅ 폴더 띄우기 옵션 체크됨
[2025-08-27 15:07:08] 🟢 프로그램 시작
[2025-08-27 15:36:10] 🟢 프로그램 시작
[2025-08-27 15:36:28] 🟢 10개 파일 선택됨
[2025-08-27 15:36:35] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\honghong\Desktop\dev\copyImage\app\main.py", line 247, in run_copy
    copy_images(file_names, source, target, self.log)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\honghong\Desktop\dev\copyImage\app\copy_utils.py", line 7, in copy_images
    os.makedirs(target_dir, exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 228, in makedirs
PermissionError: [WinError 5] 액세스가 거부되었습니다: 'C:\\Users\\myh'

[2025-08-27 15:36:52] ✅ 복사됨: img_1.png
[2025-08-27 15:36:52] ✅ 복사됨: img_2.png
[2025-08-27 15:36:52] ✅ 복사됨: img_3.png
[2025-08-27 15:36:52] ✅ 복사됨: img_4.png
[2025-08-27 15:36:52] ✅ 복사됨: img_5.png
[2025-08-27 15:36:52] ✅ 복사됨: img_6.png
[2025-08-27 15:36:52] ✅ 복사됨: img_7.png
[2025-08-27 15:36:52] ✅ 복사됨: img_8.png
[2025-08-27 15:36:52] ✅ 복사됨: img_9.png
[2025-08-27 15:36:52] ✅ 복사됨: img_10.png
[2025-08-27 15:36:52] ✅ 작업 완료!
[2025-08-27 15:42:26] 🟢 프로그램 시작
[2025-08-27 15:42:31] 🟢 PDF 생성 시작: C:\Users\honghong\Desktop\새 폴더\이미지_모음.pdf
[2025-08-27 15:42:31] ✅ PDF 저장 완료: C:\Users\honghong\Desktop\새 폴더\이미지_모음.pdf
[2025-08-27 15:43:56] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\honghong\Desktop\dev\copyImage\app\main.py", line 441, in <module>
    sys.exit(app.exec())
             ~~~~~~~~^^
KeyboardInterrupt

[2025-08-27 15:43:57] 🟢 프로그램 시작
[2025-08-27 15:44:15] 🟢 프로그램 시작
[2025-08-27 15:44:36] 🟢 프로그램 시작
[2025-08-27 15:44:38] ✅ 복사됨: img_1.png
[2025-08-27 15:44:38] ✅ 복사됨: img_2.png
[2025-08-27 15:44:38] ✅ 복사됨: img_3.png
[2025-08-27 15:44:38] ✅ 복사됨: img_4.png
[2025-08-27 15:44:38] ✅ 복사됨: img_5.png
[2025-08-27 15:44:38] ✅ 복사됨: img_6.png
[2025-08-27 15:44:38] ✅ 복사됨: img_7.png
[2025-08-27 15:44:38] ✅ 복사됨: img_8.png
[2025-08-27 15:44:38] ✅ 복사됨: img_9.png
[2025-08-27 15:44:38] ✅ 복사됨: img_10.png
[2025-08-27 15:44:38] ✅ 작업 완료!
[2025-08-27 15:44:42] 🟢 PDF 생성 시작: C:\Users\honghong\Desktop\새 폴더\이미지_모음_1.pdf
[2025-08-27 15:44:42] ✅ PDF 저장 완료: C:\Users\honghong\Desktop\새 폴더\이미지_모음_1.pdf
[2025-08-27 15:46:10] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\honghong\Desktop\dev\copyImage\app\main.py", line 442, in <module>
    sys.exit(app.exec())
             ~~~~~~~~^^
KeyboardInterrupt

[2025-08-27 15:46:12] 🟢 프로그램 시작
[2025-08-27 15:46:14] 🟢 PDF 생성 시작: C:\Users\honghong\Desktop\새 폴더\이미지_모음_2.pdf
[2025-08-27 15:46:14] ✅ PDF 저장 완료: C:\Users\honghong\Desktop\새 폴더\이미지_모음_2.pdf
[2025-08-27 15:47:13] 🟢 프로그램 시작
[2025-08-27 15:47:15] 🟢 PDF 생성 시작: C:\Users\honghong\Desktop\새 폴더\이미지_모음_3.pdf
[2025-08-27 15:47:15] ✅ PDF 저장 완료: C:\Users\honghong\Desktop\새 폴더\이미지_모음_3.pdf
[2025-08-27 15:49:33] 🟢 프로그램 시작
[2025-08-27 15:49:36] ✅ 복사됨: img_1.png
[2025-08-27 15:49:36] ✅ 복사됨: img_2.png
[2025-08-27 15:49:36] ✅ 복사됨: img_3.png
[2025-08-27 15:49:36] ✅ 복사됨: img_4.png
[2025-08-27 15:49:36] ✅ 복사됨: img_5.png
[2025-08-27 15:49:36] ✅ 복사됨: img_6.png
[2025-08-27 15:49:36] ✅ 복사됨: img_7.png
[2025-08-27 15:49:36] ✅ 복사됨: img_8.png
[2025-08-27 15:49:36] ✅ 복사됨: img_9.png
[2025-08-27 15:49:36] ✅ 복사됨: img_10.png
[2025-08-27 15:49:36] ✅ 작업 완료!
[2025-08-27 15:49:39] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\honghong\Desktop\dev\copyImage\app\main.py", line 384, in save_images_to_pdf
    for f in sorted(os.listdir(folder), key=natural_sort_key)  # natural sort 적용
             ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\honghong\Desktop\dev\copyImage\app\main.py", line 380, in natural_sort_key
    return [int(text) if text.isdigit() else text.lower() for text in re.split(r'(\d+)', s)]
                                                                      ^^
NameError: name 're' is not defined. Did you forget to import 're'?

[2025-08-27 15:50:05] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\honghong\Desktop\dev\copyImage\app\main.py", line 453, in <module>
    sys.app_window = window  # 전역에서 예외 처리용
             ^^^^^^^^^^
KeyboardInterrupt

[2025-08-27 15:50:08] 🟢 프로그램 시작
[2025-08-27 15:50:10] ✅ 복사됨: img_1.png
[2025-08-27 15:50:10] ✅ 복사됨: img_2.png
[2025-08-27 15:50:10] ✅ 복사됨: img_3.png
[2025-08-27 15:50:10] ✅ 복사됨: img_4.png
[2025-08-27 15:50:10] ✅ 복사됨: img_5.png
[2025-08-27 15:50:10] ✅ 복사됨: img_6.png
[2025-08-27 15:50:10] ✅ 복사됨: img_7.png
[2025-08-27 15:50:10] ✅ 복사됨: img_8.png
[2025-08-27 15:50:10] ✅ 복사됨: img_9.png
[2025-08-27 15:50:10] ✅ 복사됨: img_10.png
[2025-08-27 15:50:10] ✅ 작업 완료!
[2025-08-27 15:50:13] 🟢 PDF 생성 시작: C:\Users\honghong\Desktop\새 폴더\이미지_모음_4.pdf
[2025-08-27 15:50:13] ✅ PDF 저장 완료: C:\Users\honghong\Desktop\새 폴더\이미지_모음_4.pdf
[2025-08-27 15:50:32] 🟢 PDF 생성 시작: C:\Users\honghong\Desktop\새 폴더\이미지_모음_5.pdf
[2025-08-27 15:50:32] ✅ PDF 저장 완료: C:\Users\honghong\Desktop\새 폴더\이미지_모음_5.pdf
[2025-08-27 15:53:46] 🟢 프로그램 시작
[2025-08-27 15:55:20] 🟢 PDF 생성 시작: C:\Users\honghong\Desktop\새 폴더\이미지_모음_6.pdf
[2025-08-27 15:55:20] ✅ PDF 저장 완료: C:\Users\honghong\Desktop\새 폴더\이미지_모음_6.pdf
[2025-08-27 15:56:02] 🟢 PDF 생성 시작: C:\Users\honghong\Desktop\새 폴더\이미지_모음_7.pdf
[2025-08-27 15:56:02] ✅ PDF 저장 완료: C:\Users\honghong\Desktop\새 폴더\이미지_모음_7.pdf
[2025-08-27 23:03:09] 🟢 프로그램 시작
[2025-08-27 23:03:43] 🟢 21개 파일 선택됨
[2025-08-27 23:03:45] ✅ 복사됨: image-1.png
[2025-08-27 23:03:45] ✅ 복사됨: image-2.png
[2025-08-27 23:03:45] ✅ 복사됨: image-3.png
[2025-08-27 23:03:45] ✅ 복사됨: image-4.png
[2025-08-27 23:03:45] ✅ 복사됨: image-5.png
[2025-08-27 23:03:45] ✅ 복사됨: image-6.png
[2025-08-27 23:03:45] ✅ 복사됨: image-7.png
[2025-08-27 23:03:45] ✅ 복사됨: image-8.png
[2025-08-27 23:03:45] ✅ 복사됨: image-9.png
[2025-08-27 23:03:45] ✅ 복사됨: image-10.png
[2025-08-27 23:03:45] ✅ 복사됨: image-11.png
[2025-08-27 23:03:45] ✅ 복사됨: image-12.png
[2025-08-27 23:03:45] ✅ 복사됨: image-13.png
[2025-08-27 23:03:45] ✅ 복사됨: image-14.png
[2025-08-27 23:03:45] ✅ 복사됨: image-15.png
[2025-08-27 23:03:45] ✅ 복사됨: image-16.png
[2025-08-27 23:03:45] ✅ 복사됨: image-17.png
[2025-08-27 23:03:45] ✅ 복사됨: image-18.png
[2025-08-27 23:03:45] ✅ 복사됨: image-19.png
[2025-08-27 23:03:45] ✅ 복사됨: image-20.png
[2025-08-27 23:03:45] ✅ 복사됨: image-21.png
[2025-08-27 23:03:45] ✅ 작업 완료!
[2025-08-27 23:03:46] 🟢 PDF 생성 시작: C:/Users/hong/Desktop/nextjs/copy\이미지_모음.pdf
[2025-08-27 23:03:47] ✅ PDF 저장 완료: C:/Users/hong/Desktop/nextjs/copy\이미지_모음.pdf
[2025-08-28 13:46:06] 🟢 프로그램 시작
[2025-08-28 13:48:13] ❌ 폴더 띄우기 옵션 체크 해제됨
[2025-08-28 13:48:16] ✅ 복사됨: image-1.png
[2025-08-28 13:48:16] ✅ 복사됨: image-2.png
[2025-08-28 13:48:16] ✅ 복사됨: image-3.png
[2025-08-28 13:48:16] ✅ 복사됨: image-4.png
[2025-08-28 13:48:16] ✅ 복사됨: image-5.png
[2025-08-28 13:48:16] ✅ 복사됨: image-6.png
[2025-08-28 13:48:16] ✅ 복사됨: image-7.png
[2025-08-28 13:48:16] ✅ 복사됨: image-8.png
[2025-08-28 13:48:16] ✅ 복사됨: image-9.png
[2025-08-28 13:48:16] ✅ 복사됨: image-10.png
[2025-08-28 13:48:16] ✅ 복사됨: image-11.png
[2025-08-28 13:48:16] ✅ 복사됨: image-12.png
[2025-08-28 13:48:16] ✅ 복사됨: image-13.png
[2025-08-28 13:48:16] ✅ 복사됨: image-14.png
[2025-08-28 13:48:16] ✅ 복사됨: image-15.png
[2025-08-28 13:48:16] ✅ 복사됨: image-16.png
[2025-08-28 13:48:16] ✅ 복사됨: image-17.png
[2025-08-28 13:48:16] ✅ 복사됨: image-18.png
[2025-08-28 13:48:16] ✅ 복사됨: image-19.png
[2025-08-28 13:48:16] ✅ 복사됨: image-20.png
[2025-08-28 13:48:16] ✅ 복사됨: image-21.png
[2025-08-28 13:48:16] ✅ 작업 완료!
[2025-08-28 13:48:18] 🟢 PDF 생성 시작: C:\Users\hong\Desktop\nextjs\copy\이미지_모음_1.pdf
[2025-08-28 13:48:19] ✅ PDF 저장 완료: C:\Users\hong\Desktop\nextjs\copy\이미지_모음_1.pdf
[2025-08-28 13:49:23] 🟢 프로그램 시작
[2025-08-28 14:16:26] 🟢 프로그램 시작
[2025-08-28 14:16:30] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\hong\Desktop\nextjs\copyImage\app\main.py", line 389, in save_images_to_pdf_with_template
    for f in sorted(os.listdir(folder), key=natural_sort_key)
                                            ^^^^^^^^^^^^^^^^
NameError: name 'natural_sort_key' is not defined

[2025-08-28 14:17:29] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\hong\Desktop\nextjs\copyImage\app\main.py", line 389, in save_images_to_pdf_with_template
    for f in sorted(os.listdir(folder), key=self.natural_sort_key)
                                            ^^^^^^^^^^^^^^^^
NameError: name 'natural_sort_key' is not defined

[2025-08-28 14:17:34] 🟢 프로그램 시작
[2025-08-28 14:17:35] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\hong\Desktop\nextjs\copyImage\app\main.py", line 389, in save_images_to_pdf_with_template
    for f in sorted(os.listdir(folder), key=self.natural_sort_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ImageCopyApp.natural_sort_key() takes 1 positional argument but 2 were given

[2025-08-28 14:19:34] 🟢 프로그램 시작
[2025-08-28 14:19:36] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\hong\Desktop\nextjs\copyImage\app\main.py", line 452, in save_images_to_pdf_with_template
    base_page.merge_page(overlay_pdf.pages[0])
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'merge_page'

[2025-08-28 14:22:37] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\hong\Desktop\nextjs\copyImage\app\main.py", line 561, in <module>
    window.show()
             ^^^^^
KeyboardInterrupt

[2025-08-28 14:22:39] 🟢 프로그램 시작
[2025-08-28 14:24:07] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\hong\Desktop\nextjs\copyImage\app\main.py", line 562, in <module>
KeyboardInterrupt

[2025-08-28 14:24:09] 🟢 프로그램 시작
[2025-08-28 14:25:27] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\hong\Desktop\nextjs\copyImage\app\main.py", line 559, in <module>
    window.show()
             ^^^^^
KeyboardInterrupt

[2025-08-28 14:25:29] 🟢 프로그램 시작
[2025-08-28 14:28:33] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\hong\Desktop\nextjs\copyImage\app\main.py", line 560, in <module>
    subprocess.Popen(["xdg-open", os.path.abspath(folder)])
     ^^^^^^^^^^
KeyboardInterrupt

[2025-08-28 14:28:35] 🟢 프로그램 시작
[2025-08-28 14:30:10] 🟢 프로그램 시작
[2025-08-28 14:30:31] 🟢 프로그램 시작
[2025-08-28 14:31:06] 🟢 프로그램 시작
[2025-08-28 14:32:23] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\hong\Desktop\nextjs\copyImage\app\main.py", line 569, in <module>
    sys.exit(app.exec())
             ^^^^^^^^^^
KeyboardInterrupt

